nautobot_plugin_evpn/urls.py
from django.urls import path
from nautobot.extras.views import ObjectChangeLogView, ObjectNotesView
from nautobot_plugin_evpn import models, views

app_name = "evpn"

urlpatterns = [
    # EVPNService
    path("evpnservice/", views.EVPNServiceListView.as_view(), name="evpnservice_list"),
    path(
        "evpnservice/add/",
        views.EVPNServiceEditView.as_view(),
        name="evpnservice_add",
    ),
    path(
        "evpnservice/edit/",
        views.EVPNServiceBulkEditView.as_view(),
        name="evpnservice_bulk_edit",
    ),
    path(
        "evpnservice/delete/",
        views.EVPNServiceBulkDeleteView.as_view(),
        name="evpnservice_bulk_delete",
    ),
    path(
        "evpnservice/<uuid:pk>/",
        views.EVPNServiceDetailView.as_view(),
        name="evpnservice",
    ),
    path(
        "evpnservice/<uuid:pk>/edit/",
        views.EVPNServiceEditView.as_view(),
        name="evpnservice_edit",
    ),
    path(
        "evpnservice/<uuid:pk>/delete/",
        views.EVPNServiceDeleteView.as_view(),
        name="evpnservice_delete",
    ),
    path(
        "evpnservice/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="evpnservice_changelog",
        kwargs={"model": models.EVPNService},
    ),
    path(
        "evpnservice/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="evpnservice_notes",
        kwargs={"model": models.EVPNService},
    ),
    # VNI
    path("vni/", views.VNIListView.as_view(), name="vni_list"),
    path(
        "vni/add/",
        views.VNIEditView.as_view(),
        name="vni_add",
    ),
    path(
        "vni/edit/",
        views.VNIBulkEditView.as_view(),
        name="vni_bulk_edit",
    ),
    path(
        "vni/delete/",
        views.VNIBulkDeleteView.as_view(),
        name="vni_bulk_delete",
    ),
    path(
        "vni/<uuid:pk>/",
        views.VNIDetailView.as_view(),
        name="vni",
    ),
    path(
        "vni/<uuid:pk>/edit/",
        views.VNIEditView.as_view(),
        name="vni_edit",
    ),
    path(
        "vni/<uuid:pk>/delete/",
        views.VNIDeleteView.as_view(),
        name="vni_delete",
    ),
    path(
        "vni/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="vni_changelog",
        kwargs={"model": models.VNI},
    ),
    path(
        "vni/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="vni_notes",
        kwargs={"model": models.VNI},
    ),
    # EVPNLayer2VRF
    path("evpnlayer2vrf/", views.EVPNLayer2VRFListView.as_view(), name="evpnlayer2vrf_list"),
    path(
        "evpnlayer2vrf/add/",
        views.EVPNLayer2VRFEditView.as_view(),
        name="evpnlayer2vrf_add",
    ),
    path(
        "evpnlayer2vrf/edit/",
        views.EVPNLayer2VRFBulkEditView.as_view(),
        name="evpnlayer2vrf_bulk_edit",
    ),
    path(
        "evpnlayer2vrf/delete/",
        views.EVPNLayer2VRFBulkDeleteView.as_view(),
        name="evpnlayer2vrf_bulk_delete",
    ),
    path(
        "evpnlayer2vrf/<uuid:pk>/",
        views.EVPNLayer2VRFDetailView.as_view(),
        name="evpnlayer2vrf",
    ),
    path(
        "evpnlayer2vrf/<uuid:pk>/edit/",
        views.EVPNLayer2VRFEditView.as_view(),
        name="evpnlayer2vrf_edit",
    ),
    path(
        "evpnlayer2vrf/<uuid:pk>/delete/",
        views.EVPNLayer2VRFDeleteView.as_view(),
        name="evpnlayer2vrf_delete",
    ),
    path(
        "evpnlayer2vrf/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="evpnlayer2vrf_changelog",
        kwargs={"model": models.EVPNLayer2VRF},
    ),
    path(
        "evpnlayer2vrf/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="evpnlayer2vrf_notes",
        kwargs={"model": models.EVPNLayer2VRF},
    ),
    # EVPNLayer3VRF
    path("evpnlayer3vrf/", views.EVPNLayer3VRFListView.as_view(), name="evpnlayer3vrf_list"),
    path(
        "evpnlayer3vrf/add/",
        views.EVPNLayer3VRFEditView.as_view(),
        name="evpnlayer3vrf_add",
    ),
    path(
        "evpnlayer3vrf/edit/",
        views.EVPNLayer3VRFBulkEditView.as_view(),
        name="evpnlayer3vrf_bulk_edit",
    ),
    path(
        "evpnlayer3vrf/delete/",
        views.EVPNLayer3VRFBulkDeleteView.as_view(),
        name="evpnlayer3vrf_bulk_delete",
    ),
    path(
        "evpnlayer3vrf/<uuid:pk>/",
        views.EVPNLayer3VRFDetailView.as_view(),
        name="evpnlayer3vrf",
    ),
    path(
        "evpnlayer3vrf/<uuid:pk>/edit/",
        views.EVPNLayer3VRFEditView.as_view(),
        name="evpnlayer3vrf_edit",
    ),
    path(
        "evpnlayer3vrf/<uuid:pk>/delete/",
        views.EVPNLayer3VRFDeleteView.as_view(),
        name="evpnlayer3vrf_delete",
    ),
    path(
        "evpnlayer3vrf/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="evpnlayer3vrf_changelog",
        kwargs={"model": models.EVPNLayer3VRF},
    ),
    path(
        "evpnlayer3vrf/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="evpnlayer3vrf_notes",
        kwargs={"model": models.EVPNLayer3VRF},
    ),
    # EVPNAttachmentPoint
    path("evpnattachmentpoint/", views.EVPNAttachmentPointListView.as_view(), name="evpnattachmentpoint_list"),
    path(
        "evpnattachmentpoint/add/",
        views.EVPNAttachmentPointEditView.as_view(),
        name="evpnattachmentpoint_add",
    ),
    path(
        "evpnattachmentpoint/edit/",
        views.EVPNAttachmentPointBulkEditView.as_view(),
        name="evpnattachmentpoint_bulk_edit",
    ),
    path(
        "evpnattachmentpoint/delete/",
        views.EVPNAttachmentPointBulkDeleteView.as_view(),
        name="evpnattachmentpoint_bulk_delete",
    ),
    path(
        "evpnattachmentpoint/<uuid:pk>/",
        views.EVPNAttachmentPointDetailView.as_view(),
        name="evpnattachmentpoint",
    ),
    path(
        "evpnattachmentpoint/<uuid:pk>/edit/",
        views.EVPNAttachmentPointEditView.as_view(),
        name="evpnattachmentpoint_edit",
    ),
    path(
        "evpnattachmentpoint/<uuid:pk>/delete/",
        views.EVPNAttachmentPointDeleteView.as_view(),
        name="evpnattachmentpoint_delete",
    ),
    path(
        "evpnattachmentpoint/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="evpnattachmentpoint_changelog",
        kwargs={"model": models.EVPNAttachmentPoint},
    ),
    path(
        "evpnattachmentpoint/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="evpnattachmentpoint_notes",
        kwargs={"model": models.EVPNAttachmentPoint},
    ),
    # EVPNEthernetSegment
    path("evpnethernetsegment/", views.EVPNEthernetSegmentListView.as_view(), name="evpnethernetsegment_list"),
    path(
        "evpnethernetsegment/add/",
        views.EVPNEthernetSegmentEditView.as_view(),
        name="evpnethernetsegment_add",
    ),
    path(
        "evpnethernetsegment/edit/",
        views.EVPNEthernetSegmentBulkEditView.as_view(),
        name="evpnethernetsegment_bulk_edit",
    ),
    path(
        "evpnethernetsegment/delete/",
        views.EVPNEthernetSegmentBulkDeleteView.as_view(),
        name="evpnethernetsegment_bulk_delete",
    ),
    path(
        "evpnethernetsegment/<uuid:pk>/",
        views.EVPNEthernetSegmentDetailView.as_view(),
        name="evpnethernetsegment",
    ),
    path(
        "evpnethernetsegment/<uuid:pk>/edit/",
        views.EVPNEthernetSegmentEditView.as_view(),
        name="evpnethernetsegment_edit",
    ),
    path(
        "evpnethernetsegment/<uuid:pk>/delete/",
        views.EVPNEthernetSegmentDeleteView.as_view(),
        name="evpnethernetsegment_delete",
    ),
    path(
        "evpnethernetsegment/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="evpnethernetsegment_changelog",
        kwargs={"model": models.EVPNEthernetSegment},
    ),
    path(
        "evpnethernetsegment/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="evpnethernetsegment_notes",
        kwargs={"model": models.EVPNEthernetSegment},
    ),
    # EVPNEthernetSegmentLAGInterface
    path(
        "evpnesilaginterface/",
        views.EVPNEthernetSegmentLAGInterfaceListView.as_view(),
        name="evpnethernetsegmentlaginterface_list",
    ),
    path(
        "evpnesilaginterface/add/",
        views.EVPNEthernetSegmentLAGInterfaceEditView.as_view(),
        name="evpnethernetsegmentlaginterface_add",
    ),
    path(
        "evpnesilaginterface/edit/",
        views.EVPNEthernetSegmentLAGInterfaceBulkEditView.as_view(),
        name="evpnethernetsegmentlaginterface_bulk_edit",
    ),
    path(
        "evpnesilaginterface/delete/",
        views.EVPNEthernetSegmentLAGInterfaceBulkDeleteView.as_view(),
        name="evpnethernetsegmentlaginterface_bulk_delete",
    ),
    path(
        "evpnesilaginterface/<uuid:pk>/",
        views.EVPNEthernetSegmentLAGInterfaceDetailView.as_view(),
        name="evpnethernetsegmentlaginterface",
    ),
    path(
        "evpnesilaginterface/<uuid:pk>/edit/",
        views.EVPNEthernetSegmentLAGInterfaceEditView.as_view(),
        name="evpnethernetsegmentlaginterface_edit",
    ),
    path(
        "evpnesilaginterface/<uuid:pk>/delete/",
        views.EVPNEthernetSegmentLAGInterfaceDeleteView.as_view(),
        name="evpnethernetsegmentlaginterface_delete",
    ),
    path(
        "evpnesilaginterface/<uuid:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="evpnethernetsegmentlaginterface_changelog",
        kwargs={"model": models.EVPNEthernetSegmentLAGInterface},
    ),
    path(
        "evpnesilaginterface/<uuid:pk>/notes/",
        ObjectNotesView.as_view(),
        name="evpnethernetsegmentlaginterface_notes",
        kwargs={"model": models.EVPNEthernetSegmentLAGInterface},
    ),
]

nautobot_plugin_evpn/models.py
import re

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.core.validators import MaxValueValidator, MinValueValidator, MinLengthValidator
from nautobot.core.fields import AutoSlugField
from nautobot.core.models.generics import PrimaryModel
from nautobot.dcim.models.devices import Device, Interface


class VNI(PrimaryModel):
    vni = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(16777216)], unique=True)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["vni"]
        verbose_name = "VXLAN VNI"
        verbose_name_plural = "VXLAN VNIs"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:vni", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.vni}"


class EVPNLayer2VRF(PrimaryModel):
    EVPN_VRF_TYPES = [("vlan_aware", "VLAN Aware Bundle")]
    EVPN_ENCAPSULATION = [("vxlan", "VXLAN")]

    vrf = models.OneToOneField("ipam.vrf", on_delete=models.RESTRICT)
    type = models.CharField(max_length=20, choices=EVPN_VRF_TYPES)
    encapsulation = models.CharField(max_length=20, choices=EVPN_ENCAPSULATION)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["vrf"]
        verbose_name = "EVPN Layer 2 VRF"
        verbose_name_plural = "EVPN Layer 2 VRFs"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnlayer2vrf", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.vrf}"


class EVPNLayer3VRF(PrimaryModel):
    EVPN_VRF_TYPES = [("evpn_l3", "EVPN L3VPN")]
    EVPN_ENCAPSULATION = [("vxlan", "VXLAN")]

    type = models.CharField(max_length=20, choices=EVPN_VRF_TYPES)
    encapsulation = models.CharField(max_length=20, choices=EVPN_ENCAPSULATION)
    vrf = models.OneToOneField("ipam.vrf", on_delete=models.RESTRICT)
    vni = models.OneToOneField(VNI, on_delete=models.RESTRICT)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["vrf"]
        verbose_name = "EVPN Layer 3 VRF"
        verbose_name_plural = "EVPN Layer 3 VRFs"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnlayer3vrf", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.vrf}"


class EVPNService(PrimaryModel):
    name = models.CharField(max_length=25)
    slug = AutoSlugField(populate_from="name")
    layer2_vrf = models.ForeignKey(EVPNLayer2VRF, on_delete=models.RESTRICT)
    vni = models.OneToOneField(VNI, on_delete=models.RESTRICT)
    layer3_vrf = models.ForeignKey(EVPNLayer3VRF, on_delete=models.RESTRICT, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True)
    tenant = models.ForeignKey(to="tenancy.tenant", on_delete=models.RESTRICT, blank=True, null=True)

    class Meta:
        ordering = ["vni"]
        verbose_name = "EVPN Service"
        verbose_name_plural = "EVPN Services"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnservice", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.name}"


class EVPNAttachmentPoint(PrimaryModel):
    evpn_service = models.ForeignKey(EVPNService, on_delete=models.RESTRICT)
    device = models.ForeignKey(Device, on_delete=models.RESTRICT)
    interface = models.OneToOneField(Interface, on_delete=models.RESTRICT)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["evpn_service"]
        verbose_name = "EVPN Attachment Point"
        verbose_name_plural = "EVPN Attachment Points"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnattachmentpoint", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.pk}"


class EVPNLayer3Interface(PrimaryModel):
    evpn_service = models.ForeignKey(EVPNService, on_delete=models.RESTRICT)
    device = models.ForeignKey(Device, on_delete=models.RESTRICT)
    interface = models.OneToOneField(Interface, on_delete=models.RESTRICT)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["evpn_service"]
        verbose_name = "EVPN Layer 3 Interface"
        verbose_name_plural = "EVPN Layer 3 Interfaces"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnlayer3interface", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.pk}"


class EVPNEthernetSegment(PrimaryModel):
    ESI_TYPES = [
        (0, "Manual"),
        (1, "Auto from LACP"),
        (2, "Auto from STP"),
        (3, "MAC based"),
        (4, "Router ID based"),
        (5, "ASN Based"),
    ]

    type = models.IntegerField(choices=ESI_TYPES)
    esi = models.CharField(
        max_length=29, unique=True, null=True, blank=True, default=None, validators=[MinLengthValidator(29)]
    )
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["esi"]
        verbose_name = "EVPN Ethernet Segment Identifier"
        verbose_name_plural = "EVPN Segment Identifiers"

    def __str__(self) -> str:
        if self.esi and len(self.esi) > 0:
            return f"{self.esi}"
        else:
            return f"{self.ESI_TYPES[self.type][1]}"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnethernetsegment", kwargs={"pk": self.pk})

    def clean(self):
        if self.esi:
            if not re.match("^[a-fA-F0-9]{2}(:[a-fA-F0-9]{2}){9}$", self.esi):
                raise ValidationError("ESI not a valid format, match be like 00:11:22:33:44:55:66:77:88:99.")

        if self.type == 0 and not re.match("^00:", self.esi):
            raise ValidationError("When ESI Type is Manual, ESI must start '00'.")

        if self.type == 1 and self.esi != None:
            raise ValidationError("When type is Auto from LACP, ESI must be left blank.")

        if self.type == 2 and self.esi != None:
            raise ValidationError("When type is Auto from STP, ESI must be left blank.")

        if self.type == 3 and self.esi != None and not re.match("^03:", self.esi):
            raise ValidationError(
                "When using a MAC based ESI type and manually specifying the value, it must start with '03'."
            )

        if self.type == 4 and self.esi != None and not re.match("^04:", self.esi):
            raise ValidationError(
                "When using a Router ID based ESI type and manually specifying the value, it must start with '04'."
            )

        if self.type == 5 and self.esi != None and not re.match("^05:", self.esi):
            raise ValidationError(
                "When using an ASN based ESI type and manually specifying the value, it must start with '05'."
            )

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)


# class EVPNVirtualAddresses(PrimaryModel):
#    EVPN_VIRTUAL_ADDRESS_TYPE = [("vga", "Virtual Gateway Address"), ("anycast", "Anycast Address")]
#    evpn_service = models.ForeignKey(EVPNService, on_delete=models.RESTRICT)
#    type = models.CharField(max_length=20, choices=EVPN_VIRTUAL_ADDRESS_TYPE)
#    ipv4_address=models.


class EVPNEthernetSegmentLAGInterface(PrimaryModel):
    esi = models.ForeignKey(EVPNEthernetSegment, on_delete=models.RESTRICT)
    device = models.ForeignKey(Device, on_delete=models.RESTRICT)
    interface = models.ForeignKey(Interface, on_delete=models.RESTRICT)
    description = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["esi"]
        verbose_name = "EVPN ESI-LAG"
        verbose_name_plural = "EVPN ESI-LAGs"

    def get_absolute_url(self):
        return reverse("plugins:nautobot_plugin_evpn:evpnethernetsegmentlaginterface", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.pk}"

nautobot_plugin_evpn/templates/nautobot_plugin_evpn/evpnattachmentpoint_edit.html
{% extends 'generic/object_edit.html' %}

{% load static %}
{% load form_helpers %}
{% load helpers %}

{% block form %}
 <div class="panel panel-default">
        <div class="panel-heading"><strong>EVPN Attachment Point</strong></div>
        <div class="panel-body">
            {% render_field form.evpn_service %}
            {% render_field form.device %}
            {% render_field form.interface %}
            {% render_field form.description %}
        </div>
    </div>
{% endblock %}

nautobot_plugin_evpn/templates/nautobot_plugin_evpn/evpnlayer2vrf.html
{% extends 'base.html' %}
{% load buttons %}
{% load static %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

{% block title %}{{ object }}{% endblock %}

{% block header %}
<div class="row noprint">
    <div class="col-sm-8 col-md-9">
        <ol class="breadcrumb">
            <li><a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer2vrf_list' %}">EVPN Layer 2 VRFs</a></li>
            <li>{{ object }}</li>
        </ol>
    </div>
    <div class="col-sm-4 col-md-3">
        <form action="{% url 'plugins:nautobot_plugin_evpn:evpnlayer2vrf_list' %}" method="get">
            <div class="input-group">
                <input type="text" name="q" class="form-control" />
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="mdi mdi-magnify" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="pull-right noprint">
    {% if perms.nautobot_plugin_evpn.edit_notice %}
    <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer2vrf_edit' pk=object.id %}" class="btn btn-warning">
        <span class="mdi mdi-pencil" aria-hidden="true"></span> Edit
    </a>
    {% endif %}
    {% if perms.nautobot_plugin_evpn.delete_notice %}
    <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer2vrf_delete' pk=object.id %}" class="btn btn-danger">
        <span class="mdi mdi-trash-can-outline" aria-hidden="true"></span> Delete
    </a>
    {% endif %}
</div>
<h1>{{ object }}</h1>
{% include 'inc/created_updated.html' with obj=object %}
<div class="pull-right noprint">
    {% custom_links object %}
</div>
<ul class="nav nav-tabs">
    <li role="presentation" {% if active_tab == 'main' %} class="active" {% endif %}>
        <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer2vrf' pk=object.id %}">EVPN Layer 2 VRF</a>
    </li>
    {% if perms.extras.view_objectchange %}
    <li role="presentation" {% if active_tab == 'changelog' %} class="active" {% endif %}>
        <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer2vrf_changelog' pk=object.id %}">Change Log</a>
    </li>
    {% endif %}
</ul>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>EVPN Layer 2 VRF</strong>
            </div>
            <table class="table table-hover panel-body attr-table">
                <tr>
                    <td>VRF</td>
                    <td>{{ object.vrf }}</td>
                </tr>
                <tr>
                    <td>Type</td>
                    <td>{{ object.get_type_display }}</td>
                </tr>
                <tr>
                    <td>Encapsulation</td>
                    <td>{{ object.get_encapsulation_display }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ object.description|placeholder }}</td>
                </tr>


            </table>
        </div>
        {% include 'inc/custom_fields_panel.html' %}
        {% include 'inc/relationships_panel.html' %}
        {% plugin_left_page object %}
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        {% plugin_full_width_page object %}
    </div>
</div>
{% endblock %}

nautobot_plugin_evpn/templates/nautobot_plugin_evpn/evpnlayer3vrf.html
{% extends 'base.html' %}
{% load buttons %}
{% load static %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

{% block title %}{{ object }}{% endblock %}

{% block header %}
<div class="row noprint">
    <div class="col-sm-8 col-md-9">
        <ol class="breadcrumb">
            <li><a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer3vrf_list' %}">EVPN Layer 3 VRFs</a></li>
            <li>{{ object }}</li>
        </ol>
    </div>
    <div class="col-sm-4 col-md-3">
        <form action="{% url 'plugins:nautobot_plugin_evpn:evpnlayer3vrf_list' %}" method="get">
            <div class="input-group">
                <input type="text" name="q" class="form-control" />
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <span class="mdi mdi-magnify" aria-hidden="true"></span>
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="pull-right noprint">
    {% if perms.nautobot_plugin_evpn.edit_notice %}
    <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer3vrf_edit' pk=object.id %}" class="btn btn-warning">
        <span class="mdi mdi-pencil" aria-hidden="true"></span> Edit
    </a>
    {% endif %}
    {% if perms.nautobot_plugin_evpn.delete_notice %}
    <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer3vrf_delete' pk=object.id %}" class="btn btn-danger">
        <span class="mdi mdi-trash-can-outline" aria-hidden="true"></span> Delete
    </a>
    {% endif %}
</div>
<h1>{{ object }}</h1>
{% include 'inc/created_updated.html' with obj=object %}
<div class="pull-right noprint">
    {% custom_links object %}
</div>
<ul class="nav nav-tabs">
    <li role="presentation" {% if active_tab == 'main' %} class="active" {% endif %}>
        <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer3vrf' pk=object.id %}">EVPN Layer 3 VRF</a>
    </li>
    {% if perms.extras.view_objectchange %}
    <li role="presentation" {% if active_tab == 'changelog' %} class="active" {% endif %}>
        <a href="{% url 'plugins:nautobot_plugin_evpn:evpnlayer3vrf_changelog' pk=object.id %}">Change Log</a>
    </li>
    {% endif %}
</ul>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>EVPN Layer 3 VRF</strong>
            </div>
            <table class="table table-hover panel-body attr-table">
                <tr>
                    <td>VRF</td>
                    <td>{{ object.vrf }}</td>
                </tr>
                <tr>
                    <td>Type</td>
                    <td>{{ object.get_type_display }}</td>
                </tr>
                <tr>
                    <td>Encapsulation</td>
                    <td>{{ object.get_encapsulation_display }}</td>
                </tr>
                <tr>
                    <td>VNI</td>
                    <td>{{ object.vni }}</td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>{{ object.description|placeholder }}</td>
                </tr>


            </table>
        </div>
        {% include 'inc/custom_fields_panel.html' %}
        {% include 'inc/relationships_panel.html' %}
        {% plugin_left_page object %}
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        {% plugin_full_width_page object %}
    </div>
</div>
{% endblock %}